path: /home/msi/Dev/ml/seni_komputer/quiz2/dataset
train: ktp_new/images
val: ktp_new/images

#Classes
names:
  0: Nafis
  1: Iskandar
  2: Arya
  3: Eka Mahendra
  4: Jidan Jamil
  5: Ramadhani
  6: Syihab
  7: Aido Luthfi
  8: Ahlal Wafa
  #   0: Antonius Natael
  # 1: Debby
  # 2: Eko Nursetyo
  # 3: Fauzan Izha
  # 4: Hartono
  # 5: Hendra Eka
  # 6: Prima Gravigardia
  # 7: Riyanto SE
  # 8: Teguh Wibawanto
  # 9: Thesy Bonita